# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t83', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t83',
            old_name='t83_shart',
            new_name='t83_short',
        ),
    ]
